export default interface Company {
  id ?: string|number,
  photo ?: string,
  name ?: string,
  description  ?: string,
  email     ?: string,
  address ?: string,
  country  ?: string,
  postal_code  ?: string|null,
  city ?: string,
  tel      ?: string,
  number_of_employees   ?: number|string,
  created_at ?: string,
  updated_at ?: string,
}