export default interface Company {
  id ?: string|number,
  logo ?: any,
  photo ?: any,
  name ?: string,
  description  ?: string,
  email     ?: string,
  address ?: string,
  country  ?: string,
  active ?: boolean,
  postal_code  ?: string|null,
  city ?: string,
  tel      ?: string|null,
  NUI      ?: string|null,
  RCCM      ?: string|null,
  number_of_employees   ?: number|string,
  created_at ?: string,
  updated_at ?: string,
}